apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deploy
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 886863818383.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000